### ISSUE TITLE
failed install on 7.3.1

### ISSUE THREAD

**Issue by AussieInSeattle** [wkallhof/Simple301#1]
Installed via NuGet - fails as it tries to install 7.3.0-RC?

**Comment by minirobbo** [comment]
For me, nuget didnt copy the DLL to the bin folder

**Comment by AussieInSeattle** [comment]
correct - if it fails to install, you wont get the dll in your bin folder :-)

seems to be an issue with the Dependency:
UmbracoCms (≥ 7.3.0-RC)

Seems that NuGet gets confused and doesnt think that 7.3.1 is >= 7.3.0-RC?

**Comment by wkallhof** [comment]
I have updated the latest version to remove the dependency within my nuspec and update the code to use the latest UmbracoCms.Core v7.3.1 . Let me know if you continue to have issues.
