### ISSUE TITLE
External Redirects

### ISSUE THREAD

**Issue by bgilbert6** [wkallhof/Simple301#10]
Is there a way to get simple 301 to work with external redirects to another domain?

**Comment by wkallhof** [comment]
@bgilbert6 I have updated the code to check for external redirects and redirect properly. You can find this in the latest 1.0.7 version.

**Comment by Kemunch** [comment]
Great – thanks for your quick fix!

Fra: Wade Kallhoff [mailto:notifications@github.com]
Sendt: 27. juli 2016 18:47
Til: wkallhof/Simple301 <Simple301@noreply.github.com>
Emne: Re: [wkallhof/Simple301] External Redirects (#10)


@bgilbert6<https://github.com/bgilbert6> I have updated the code to check for external redirects and redirect properly. You can find this in the latest 1.0.7 version.
