### ISSUE TITLE
Duplicate redirects

### ISSUE THREAD

**Issue by revolution42** [wkallhof/Simple301#12]
I seem to have an issue when there are duplicate redirects the website is brought down.

**Comment by bgilbert6** [comment]
Make sure you aren't accidentally creating a redirect loop. Such as /index points to /default which points to / which points to /index etc. Does it give you an error?

**Comment by revolution42** [comment]
This is what I first checked, removing the duplicate from the database fixed the issue.

**Comment by wkallhof** [comment]
@revolution42 I'll look into reproducing the issue. I believe that there is validation to ensure that loops are not created but I can verify.

**Comment by wkallhof** [comment]
@revolution42 I have updated the code to detect redirect loops ( I had to dust off my algorithms analysis school book and use Floyd's Loop Detection algorithm). This should prevent users from indirectly creating redirect loops. You can find these updates in the latest 1.0.7 version.
