### ISSUE TITLE
Regex pattern support / catchall rules

### ISSUE THREAD

**Issue by BarryFogarty** [wkallhof/Simple301#14]
Hey, great package, would be even more useful if it was possible to create pattern or wildcard-matched rules though, for instance match all requests below a certain path.  Is that possible, or planned in an upcoming release?

**Comment by wkallhof** [comment]
Hey @BarryFogarty ,

I just released v1.0.8 which includes regex support. Try it out and let me know how it works.

- Wade

**Comment by BarryFogarty** [comment]
Works great Wade!  Thanks for adding so quickly.  :+1:
