### ISSUE TITLE
Users without Administrator permission are unable to see any redirects

### ISSUE THREAD

**Issue by jonsamwell** [wkallhof/Simple301#15]
Hi,

Thanks for this plugin it is great.  

We have an issue though where some of the redirects have been setup by a user with administrator rights and users with editor rights cannot see the redirects that were setup (they can created them but not see any that they or anyone else setup).  Giving the users who cannot see the redirects administrator rights enables them to see all the redirects. This is a bit of a problem though as we don't want to give those users admin rights.

Thanks 

Jon

**Comment by wkallhof** [comment]
@jonsamwell ,

I suspect something else is going on here. I don't have logic that limits the results based on the authenticated users's role. I would verify that the editor user is hitting the same URL and accessing the same data that the administrator user is accessing (ex. if you had a staging and production environment that used two different databases).

Simply put, this package takes in a redirect from the CMS, stores it in memory, backs it in the database, and uses that in memory collection or redirects to determine if a URL should be redirected. At no point does it pass through an authentication filter or role check to return the list of redirects.

Let me know if you find out any other information that could help us narrow down the problem.
