### ISSUE TITLE
Browser Caching

### ISSUE THREAD

**Issue by jameskimsca** [wkallhof/Simple301#21]
Hi,

301 redirects are being cached by Chrome and Firefox.
Any plans on tackling this issue?

James

**Comment by wkallhof** [comment]
Hey @jameskimsca ,

Not much I can do to change how the browsers cache redirects. [Relevant stackoverflow post](https://superuser.com/q/304589)

This will be the case for most all redirect management tools. Make use of Icognito Mode and clearing your browser cache to get around it.

I will say "Thank You", as I had always assumed this was the result of Umbraco caching my redirects, not the browser, and it always bugged me. 

Let me know if you yourself find any solutions to this problem.
