### ISSUE TITLE
Duplicate Dashboard alias error after install.

### ISSUE THREAD

**Issue by jt3432** [wkallhof/Simple301#3]
Seem that you have the Dashboard alias set to 'Trace Logs' and I happened to already have a package with that same alias already installed. Might want to think of updated the package so the alias is set to something a bit more unique, i.e. Simple301DashboardContentSection.

**Comment by wkallhof** [comment]
@jt3432 Did you install the package through the Umbraco Community / Umbraco Package upload functionality or NuGet? I have re-packaged it to change "Trace Logs" to "Manage Redirects". Give that a shot to see if it fixes the problem. (I also manage a package called uLogs that allows you to view the Trace Logs, hence the crossover).

**Comment by jt3432** [comment]
@wkallhof Thanks for the reply and the advise. I already figured out to just change the alias, just want let you know about the alias issue I ran into, but it seems you already knew about. As you can tell I am a fan of long and definitely unique aliases. I downloaded the package from our.umbraco.com the day I reported the issue. I also have the uLogs package installed so that is why I ran in to the issue. Like both packages, good job. If you have not already, you should think of submitting your 301 package to the core team, as you may know they want to add 301's to the Umbraco core in version 7.5. uLogs would be a good addition to the core also. Thanks again.
