### ISSUE TITLE
using wildcard in the old URL

### ISSUE THREAD

**Issue by GoodGuyShinsuke** [wkallhof/Simple301#36]
Hi guys, 

I'm not sure if this was working before but the user said it was working.
In the Old URL, we've entered "/about-us/our-people/*"
will this redirect everything under the our-people?
e.g.
"/about-us/our-people/james"

Sorry wasn't sure where to ask this question, this was the only place I can find in regards to this plugin.

Thank you
Shinsuke

**Comment by wkallhof** [comment]
@GoodGuyShinsuke 

I _think_ this would work if the redirect has been marked as a Regex redirect. However, I've seen it more properly done with something like `/about-us/our-people/(.*)` which uses a regex expression more commonly supported.

Let me know if that doesn't work.

**Comment by GoodGuyShinsuke** [comment]
Thank you that worked. I forgot to click the Regex tickbox (first column).
Closing the issue.
