### ISSUE TITLE
Performance at with lots of redirects?

### ISSUE THREAD

**Issue by protherj** [wkallhof/Simple301#5]
Have you tried this with hundreds or thousands of redirects?  Does it cause any memory or page load issues?  What about the back-office?  Are all the redirects loaded into the Back-office on initial load or are they lazy loaded / paged?

**Comment by wkallhof** [comment]
@protherj 

While I haven't done any load testing, I suspect it could easily handle hundreds or thousands of redirects. All redirects are stored in memory within a dictionary (and backed by the database only on application load and when adding/modifying a redirect. Never when doing a lookup). I suspect that even thousands of key value pairs would only result in a minor use of memory. The back-office scripts are set up in a way that the Simple 301 tab only loads the data when the user clicks on the tab.
