### ISSUE TITLE
Could not load type 'Umbraco.Core.Logging.LoggerResolver' - Umbraco 7.2.8

### ISSUE THREAD

**Issue by TheBekker** [wkallhof/Simple301#6]
Tried using the package on Umbraco 7.2.8, but get following error when hitting the site.
Is it not compatible with this "older" version?

Could not load type 'Umbraco.Core.Logging.LoggerResolver' from assembly 'Umbraco.Core, Version=1.0.5675.23466, Culture=neutral, PublicKeyToken=null'.

**Comment by wkallhof** [comment]
@TheBekker,

I haven't spent any time looking into making this package backwards compatible with any version under 7.3.0. In 7.3.0 they made some significant changes to their API. I utilize their LogHelper to log issues with redirects and I am assuming there are discrepancies in how that helper is resolved between 7.2.8 and 7.3.0. If you can find solution, feel free to make a pull request and I can review and merge it in to make this compatible with 7.2.*
