### ISSUE TITLE
handling other file extension urls

### ISSUE THREAD

**Issue by jakewilliamsongibedigital** [wkallhof/Simple301#7]
hey there,

we've just dropped the Simple301 package into a site and it's working a treat!

however we've hit one problem: we're trying to 301 and old classic asp page with the url:

`/results.asp?resort=stmoritz`

having debugged the code, in the 'RedirectContentFinder' it's getting this as the path:

`/error-404?404;http://localhost:62729/results.asp?resort=stmoritz`

have you hit on this before? it looks like the server is kicking in and serving out a 404 before it actually gets to umbraco?

i've had a quick play with a solution that feels kinda clunky but maybe a goer:

```
using Umbraco.Web.Routing;
using System.Linq;

namespace Simple301.Core
{
	/// <summary>
	/// Content finder to be injected at the start of the Umbraco pipeline that first
	/// looks for any redirects that path the path + query
	/// </summary>
	public class RedirectContentFinder : IContentFinder
	{
		public bool TryFindContent(PublishedContentRequest request)
		{
			//Get the requested URL path + query
			var path = request.Uri.PathAndQuery.ToLower();

			//if the url is a 404 grab the url prior to the 404
			if (request.Uri.Query.StartsWith("?404;"))
			{
				path = request.Uri.Query.Substring(NthOccurence(request.Uri.Query, '/', 3));
			}

			//Check the table
			var redirectLookupTable = RedirectRepository.GetLookupTable();
			var matchedRedirect = redirectLookupTable.ContainsKey(path) ? redirectLookupTable[path] : null;
			if (matchedRedirect == null) return false;

			//Found one, set the 301 redirect on the request and return
			request.SetRedirectPermanent(matchedRedirect.NewUrl);
			return true;
		}

		private static int NthOccurence(string s, char t, int n)
		{
			return s.TakeWhile(c => (n -= (c == t ? 1 : 0)) > 0).Count();
		}
	}
}
```

so if the query starts wit a 404, we'll get the path from the query and use that.

i did look into removing the classic asp side of things from iss but then realised that we have other file extensions like '.txt' in our 301's...

would really appreciate ya thoughts!

cheers,

jake

**Comment by wkallhof** [comment]
@jakewilliamsongibedigital 

I would want to avoid making assumptions around the 404 path returned, as that can be configurable. It might not even include "404" in the path.

It's likely that the right solution would be to setup your IIS to serve ".asp" extensions and ".txt" extensions, which would allow the URL to come through to the application, where we would catch it in Simple 301 and redirect or, if there wasn't an entry in Simple 301, it would result in an application 404, not IIS 404.

Another tricky part is if the server is set up to handle ".txt" as static files, the request might never make it to the application anyways, and would result in a 404 from the server.

I will play around with it a little bit this evening to get a better idea of how I can get this to work within reason and in a way that is applicable to everyone using this package.
