### ISSUE TITLE
Strange behaviour in umb 7.3.8

### ISSUE THREAD

**Issue by drummerboy46** [wkallhof/Simple301#8]
I've been pulling my hair out trying to get this to work in our dev build. Currently running on v7.3.8.

The JS error keeps hitting line 71 in the app.js when I attempt to add an entry with the error.

Cannot read property 'push' of undefined
    at Object.$scope.onAddRedirectResponse (app.js:71)

The item goes into the redirect DB table ok. But it won't read back out on page reload either! Something fundamentally wrong. But no idea what!

Martin

**Comment by wkallhof** [comment]
@drummerboy46 sorry for the late follow up. Were you able to get this working?

When the package initializes (when you click on the Manage Redirects tab for the first time), it makes a service call to get redirects from the server. That response is assigned to the `$scope.redirects` property. Your error points to the line `$scope.redirects.push(response.data.NewRedirect);`. To me, the error is indicating that the `redirects` property is never being set from the initial server call. 

- Do you see any other errors in your console? 
- Can you determine what the response is from the server when the app calls `backoffice/Simple301/RedirectApi/GetAll` ?
- If you navigate to `[your site url]/umbraco/backoffice/Simple301/RedirectApi/GetAll` in your browser, what do you see as the response?
