### ISSUE TITLE
unable to delete 301

### ISSUE THREAD

**Issue by jakewilliamsongibedigital** [wkallhof/Simple301#9]
hey there,

we've hit a weird error with trying to delete a 301. the interesting thing is, it only happens in the live environment! we can delete just fine locally and on our staging server...

i've added logging in and it doesn't actually hit the delete method at all on live...

```
[HttpDelete]
public DeleteRedirectResponse Delete(int id)
{
	LogHelper.Info<RedirectApiController>($"deleting {id}");
	if (id == 0) return new DeleteRedirectResponse() { Success = false, Message = "Invalid ID passed for redirect to delete" };

	try
	{
		RedirectRepository.DeleteRedirect(id);
		return new DeleteRedirectResponse() { Success = true };
	}
	catch (Exception e)
	{
		return new DeleteRedirectResponse() { Success = false, Message = "There was an error deleting the redirect : " + e.Message };
	}
}
```
the error message is just '500 - Internal server error. There is a problem with the resource you are looking for, and it cannot be displayed.' and doesn't change if i turn on/off debugging and custom errors. it's formatted with umbraco css.

is there something in the server config that maybe causing this delete to be disallowed?

cheers,

jake

**Comment by wkallhof** [comment]
@jakewilliamsongibedigital ,

Were you able to resolve this issue? Can you look at the application logs to get an idea of what the 500 error is?
